### ISSUE TITLE
FreeCAD cannot read UTF-16 encoded requirements.txt file

### ISSUE THREAD

**Issue by chennes** [j8sr0230/Nodes#73]
It may not matter to you since your dependencies are specified in package.xml, but FreeCAD cannot read your requirements.txt file because it's encoded in UTF-16, and the Addon Manager only supports UTF-8.

**Comment by j8sr0230** [comment]
Thank you for pointing this out. I have removed the requirements.txt from the project ([https://github.com/j8sr0230/Nodes/commit/74f3728b971b24923aa047114819c153267fc333](https://github.com/j8sr0230/Nodes/commit/74f3728b971b24923aa047114819c153267fc333)), because the package management works perfectly via the package.xml file.
